# DEFINE THE DATA DIRECTORY

data_storage:
  data_location: "/home/marc/msd/data/"
  pt_location: "/home/marc/msd/pt/"

aws_links:
  brain_tumor: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task01_BrainTumour.tar"
  heart: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task02_Heart.tar"
  liver: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task03_Liver.tar"
  hippo: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task04_Hippocampus.tar"
  prostata: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task05_Prostate.tar"
  lung: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task06_Lung.tar"
  pancreas: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task07_Pancreas.tar"
  vessel: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task08_HepaticVessel.tar"
  spleen: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task09_Spleen.tar"
  colon: "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task10_Colon.tar"


