# DEFINE THE DATA DIRECTORY
data_storage:
  data_location_training: "/home/marc/msd/data/"
  data_location_val: "/home/marc/msd/data/"
  data_location_test: "/home/marc/msd/data/"
  data_location_saving_test_data: "/home/marc/msd/results/"

# Defines which logging frameworks to use.
logging:
  logging_wandb: True
  logging_tensorboard: False
  logging_csv: False

# define the hyperparameters for training.
hyper_parameters:
  common_size: (1,1,100,512,512)
  batch_size: 32
  num_epochs: 100
  num_workers: 0
  lr: 0.001
  sn_mode: False
